platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'Parse'
pod 'AFNetworking', '~> 2.0'
pod 'SGNavigationProgress'
pod 'MHPrettyDate'
pod 'JSMessagesViewController'
pod 'MBXMapKit', '~> 0.2'
pod 'Canvas'

